micromentor-team/mentoring-flutter-app

.envrc
.gitignore
devenv.lock
devenv.nix
devenv.yaml

[Devenv](https://devenv.sh/) is a tool that setups development environment by installing packages, configuring them, managing services, running processes, etc. Initial definition takes care of flutter, JDK and Android SDK.
This PR is entirely optional and may be declined. In such a case I'll move commited files to `.git/info/exclude`. My hope is that it may be of some value to you as it simplifies setup of all the development tools (and setting up Android SDK is PITA). Feel free to check out the [Getting Started](https://devenv.sh/getting-started/) steps. Mind the fact that with these files already existing you need to run `devenv shell` instead of `devenv init` unless you already use [direnv](https://direnv.net/).
If merged then it's still optional to use it so if you don't want to …

Add support for devenv

---

.envrc
devenv.nix

I modified direnv instructions so that `flutter` is not installed if it's already available.

Don't reinstall flutter if it's already available

---

lib/l10n/app_en.arb
lib/main.dart
lib/widgets/screens/explore/entrepreneurs.dart
lib/widgets/screens/explore/explore.dart
lib/widgets/screens/explore/mentors.dart

This is a draft of "Explore" view. Things missing at this moment:
* Filtering (search phrase works)
* Quick match
* Entrepreneurs view
We may consider merging this as is and add tickets for missing functionality.
Additional questions/notes to the UX:
1. The quick match button is at awkward position. It is not affected by search or filtering.
2. What should the entrepreneurs view look like? Can we have a wireframe for that?
3. What should a user list item look like? What should be visible before and after expanding (tapping it)? For now I'm reusing `Users` widget in this PR.
4. The search mechanism forces refresh after every character. This is very resource consuming, especially w. r. t. network usage. We should have a button confirmation instead.
5. "Find a mentor" label does not make …

Add explore view

---

.git-hooks/pre-commit
.git-hooks/pre-push

`pre-commit` should be as lightweight as possible (people commit often and a lot). `pre-push` may be a bit more heavy so it contains all the checks ran by GitHub workflows.

Split pre-commit into pre-push and pre-commit

---

lib/main.dart

signin crashes the app when there's errors (eg. the input user doesn't exist in the database), the problem is scaffoldManager.showSnackBar in signin screen requires that a scaffold always exists

Quick fix on loading screen

---

lib/widgets/atoms/mentor_card.dart

Expanded widgets can only be child of Row, Column, or Flex, otherwise the app breaks.

Fix app breaking bug in the MentorCard widget tree

---

lib/data/models/base/base_operation.dart
lib/data/models/base/base_provider.dart
lib/data/models/user/queries/find_users.dart
lib/data/models/user/queries/get_authenticated_user.dart
lib/data/models/user/queries/get_user_profile_info.dart
lib/data/models/user/user_api.dart
lib/data/models/user/user_mock_provider.dart
lib/data/models/user/user_provider.dart
lib/main.dart
lib/utilities/errors/crash_handler.dart
lib/widgets/atoms/reminder_banner.dart
lib/widgets/organisms/user_card.dart
lib/widgets/screens/home/users_list.dart
lib/widgets/screens/profile/profile_screen.dart
lib/widgets/screens/profile/your_email.dart

The purpose of this PR is to introduce some useful OOP design patterns, strong typing, and structure into the existing GraphQL query operations for _User_. The remaining models and operations will be later refactored in the same manner if this PR is accepted.
The big motivation behind this PR is the gotcha of using GraphQL, which is that queries can return any number of fields, and so a single model class (e.g. UserModel) cannot accurately represent the response received from the server. Some queries will populate some fields of the UserModel, some will populate others, but very rarely you will have an instance with all of the fields available. Meaning that all fields of the model must be nullable, and that caller must be extremely careful to access only the fields that contain data. …

Refactor GraphQL user queries and data models

---

lib/data/models/user/queries/find_users.dart

`queryAllUsers` may return corrupted data such as a user without a `userHandle` or `avatarUrl == "" (!= null)`. It breaks the app.
This PR is not a solution to this problem but rather a temporary fix. We should think what to do in such situations.

Skip invalid entries

---

lib/utilities/errors/crash_handler.dart

Crashlytics doesn't support web. 
Disabling it for web so the app wouldn't crash when there's an error. Context: https://trello.com/c/Ji5gwDmI

Disable crashlytics for web

---

lib/data/models/base/base_provider.dart
lib/data/models/user/user_provider.dart
lib/main.dart
lib/utilities/errors/crash_handler.dart

Logging/reporting can be disabled if the error is handled manually, as is the case of the StartScreen showing the Sign In page if it fails to get the authenticated user.

Make error logging and reporting optional for Queries and Mutations

---

lib/__generated/schema/operations.graphql.dart
lib/__generated/schema/schema.graphql.dart
lib/data/models/channels/channels_provider.dart
lib/data/models/user/user_provider.dart
lib/schema/operations.graphql
lib/schema/schema.graphql
lib/widgets/atoms/invitation_tile.dart
lib/widgets/atoms/section_tile.dart
lib/widgets/molecules/invitation_section.dart
mm-mock-server/src/mocks/queries.ts
mm-mock-server/src/mocks/util/generators.ts

- Updated mock server to generate inbox invitations. Also added the jobTitle field to the user generator, and made the avatarUrl field show a random image.
- Added UserProvider query for finding users by ID.
- Added ChannelsProvider query for getting inbox invitations.
- Updated Widgets to use backend data instead of hardcoded data.
- Pointed the 'See all' button to the Inbox page.

Implement dashboard Invitations section with backend data

---

lib/__generated/schema/operations.graphql.dart
lib/data/models/user/user.dart
lib/data/models/user/user_provider.dart
lib/schema/operations.graphql
lib/schema/schema.graphql
lib/widgets/atoms/reminder_banner.dart
mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/queries.ts
mm-mock-server/src/mocks/util/generators.ts
mm-mock-server/src/mocks/util/state.ts

This PR introduces 4 minor changes:
1. Move profile completion logic to the User in the mock backend
2. ~~Don't return `null` for `getAuthenticatedUser` when the user is logged out. Do we want the mock backend to throw an error in this case in order to match the mmdata backend functionality? See [this trello task](https://trello.com/c/KeSnySPu/49-servererror-when-launching-app-without-being-logged-in) for more context.~~ no longer needed
3. Bulk updates to graphql schema, copied in directly from the Apollo Server ui.
4. ~~In the `myInbox` query, return channel messages with a channelId stored in `channels` in the `state.ts` file. I don't know if this is really necessary.~~ this was implemented in #46

Mock server profile, getAuthenticatedUser, and graphql schema updates

---

lib/constants/app_constants.dart
lib/constants/identifiers.dart
lib/main.dart
lib/utilities/errors/crash_handler.dart

- Moved Firebase initialization to the main method of the app, since Firebase will be used for more than Crashlytics.
- Ensured error logging in logCrashReport is wrapped in a try-catch to prevent logger issues caused by the logger itself.
- Ensured Firebase Crashlytics is enabled only on platforms that support it (iOS and Android).
- Centralized crash reporting into a separate sendCrashReport method for better maintainability.
- Adjusted error classification to treat Error instances as fatal but without causing app exit.
- Removed _exitApp method, leaving app exit handling to the Flutter framework.
- Added Identifiers to the app_constants library for storing identifiers like the appName.
- Conducted overall refactoring for cleaner and more efficient code.

Improvements to CrashHandler

---

.envrc
.gitignore
devenv.lock
devenv.nix

This allows the mock server to be started by running `devenv up` without worrying about installing node, npm, etc.

Add configuration for mock server to devenv

---

lib/constants/dimensions.dart
lib/l10n/app_en.arb
lib/widgets/molecules/closable_tile.dart
lib/widgets/molecules/profile_quick_view_card.dart
lib/widgets/screens/explore/invite_to_connect.dart

1. made invite-to-connect page work for both mentor and mentee user types
2. improved the invite-to-connect page UI to bring it closer to the wireframe
3. updated the profile quick view UI outline color and thickness

UI improvements on invite-to-connect page and profile-quick-view

---

mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/queries.ts
mm-mock-server/src/mocks/util/generators.ts
mm-mock-server/src/mocks/util/state.ts

Add a mock conversation so that the Chat UI can be tested more easily. The mock conversation covers the following:
- Conversation spanning multiple days
- Messages with emoji only
- Messages with text and emoji
- Replies from both sides
- Deleted message on both sides
- Edited message
- 2 unseen messages
- Allow adding new messages that persist in memory while the mock server is running
Includes some light refactoring of existing code.

Update mock server to generate a conversation with other user

---

lib/widgets/molecules/invitation_section.dart
lib/widgets/molecules/upcoming_section.dart
lib/widgets/screens/sign_in/sign_in_screen.dart
lib/widgets/screens/sign_up/sign_up_screen.dart
lib/widgets/screens/welcome/welcome_screen.dart

In case of the 'See all' button, the route didn't exist, and it now points to the corresponding page to show all received invites.

Replace remaining hardcoded routes to use the defined constants instead

---

mm-mock-server/src/mocks/mutations.ts

This allows deleting/undeleting, editing messages, creating replies, and marking messages as seen in the mock server. These changes persist as long as the server is running.
I need confirmation on the logic for the backend. I know these fields are all that is needed for the frontend, but I would like to know if there are side effects to running these operations that we need to be aware of. For example, does editing a message update the `editedAt` and `updatedAt` fields? Does deleting or undeleting a message update the `deletedAt` and `deletedBy` fields?
Also, is the backend able to tell the difference between a `deletedAt` field that is null because it wasn't set by the caller in the `updateChannelMessage` mutation, or because it was specifically set to null by the caller (to undelete the …

Create mock resolvers for replying, deleting, and updating messages

---

lib/l10n/app_en.arb
lib/utilities/scaffold_utils/appbar_factory.dart
lib/utilities/scaffold_utils/report_or_block_menu_button.dart
lib/widgets/atoms/profile_chip.dart
lib/widgets/screens/profile/profile.dart
lib/widgets/screens/profile/profile_basic_info.dart

1. Profile basic info section; displays vacation banner, user type, affiliations, company, education, etc.
2. moved three dots menu for block/report user to a separate file for code reuse
3. extended profileChip class to have an option to use primary color
Note: 
The vacation banner color may seem odd with profile page header, as figma uses primary95, which is not in the color scheme, so I'm using the closest color primaryContainer instead. I will follow up with Katy on this.
---
https://github.com/micromentor-team/mm-flutter-app/assets/100324646/5a6c30f5-389e-4b5a-973b-579d2227d13f
All fields
----
Only mandatory fields

Profile basic info section

---

lib/__generated/schema/operations_channel.graphql.dart
lib/__generated/schema/operations_message.graphql.dart
lib/__generated/schema/schema.graphql.dart
lib/providers/channels_provider.dart
lib/providers/models/chat_model.dart
lib/providers/models/inbox_chat_tile_model.dart
lib/schema/operations_channel.graphql
lib/schema/operations_message.graphql
lib/schema/schema.graphql
lib/widgets/molecules/inbox_chat_list_tile.dart
lib/widgets/molecules/invitation_section.dart
lib/widgets/screens/channel_messages/channel_messages.dart
lib/widgets/screens/inbox/inbox_chats.dart
mm-mock-server/src/mocks/queries.ts

- Update the remaining queries inside ChannelsProvider to return Future instead of Widget
- Updated the query for the channels last message to use instead Channel.latestMessage
- Some miscellaneous house keeping in related classes
Note that I tried to also implement an improved version of the query for unseen messages, but it seems that the corresponding backend query is not working as expected. This will be revised later.

Update ChannelsProvider to use async queries

---

lib/widgets/screens/profile/how_can_i_help_section.dart
lib/widgets/screens/profile/profile_about_me.dart

Hello,
This is a quick fix to the padding of the "How can I help" section of the profile. Here's what it looks like on an Android emulator.

Quick fix to change the padding of the chips in the "How can I help" section

---

lib/__generated/schema/operations_content.graphql.dart
lib/__generated/schema/operations_user.graphql.dart
lib/__generated/schema/schema.graphql.dart
lib/main.dart
lib/providers/content_provider.dart
lib/providers/user_provider.dart
lib/schema/operations_content.graphql
lib/schema/operations_user.graphql
lib/schema/schema.graphql
lib/widgets/atoms/reminder_banner.dart
mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/queries.ts
mm-mock-server/src/mocks/util/constants.ts
mm-mock-server/src/mocks/util/generators.ts
mm-mock-server/src/mocks/util/state.ts

This PR contains the following edits:
- Updated graphql schema to include some random updates from last few weeks, including pagination, sorting, and other options. See this PR in the backend for more context on those options: https://github.com/micromentor-team/mmdata/pull/239 
- Updates to mock server to keep up with the above schema changes, already reviewed in #84
- Added content provider, which includes static options like Countries, Languages, Company Stages, Company Types, Expertises, Industries, some preset options for Genders, and "Education Levels". Later, it may provide additional options. Countries may be broken out into a separate Location provider once we determine how States/Cities are going to work.
- Added 2 queries to the User provider which return fields specific to …

GraphQL Schema updates with options/content

---

lib/__generated/schema/operations_user.graphql.dart
lib/l10n/app_en.arb
lib/providers/user_provider.dart
lib/schema/operations_user.graphql
lib/utilities/utility.dart
lib/widgets/screens/sign_in/sign_in_screen.dart
lib/widgets/screens/sign_up/sign_up_screen.dart
pubspec.lock

- Changes to UUID so it doesn't assign a new UUID on every login, only when there is no UUID
- Some signup fixes (send UUID, and fallback to `createdAt` since there is a race condition with the assignment of `updatedAt`)
I thought there were some issues with UUIDs and having multiple user logins on the same device. However, we can create as many `UserDevice`s in the backend with the same UUID, so this is fine.
If anyone is curious, it's not particularly important but I decided to rely on a generated UUID rather than the Android/iOS ones which are unique to each app signing key. Using a generated UUID makes it so the Play Store won't flag our app as tracking users' hardware devices. Some discussion of that can be found in this popular Flutter plugin which removed that feature. ([this …

Fix bugs on signup screen, UUID updates

---

lib/main.dart
lib/providers/models/explore_card_filters_model.dart
lib/widgets/atoms/explore_filter.dart
lib/widgets/molecules/recommended_mentors_filters.dart
lib/widgets/molecules/recommended_mentors_filters_advanced.dart

We are using the convention that models are ChangeNotifiers for specific UI components, and the 'Providers' are GraphQL interfaces. Renaming and moving to 'models' folder to avoid confusion.

Rename ExploreCardFilterProvider to ExploreCardFilterModel

---

lib/main.dart
mm-mock-server/package-lock.json
mm-mock-server/package.json
mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/subscriptions.ts
mm-mock-server/src/mocks/util/state.ts
mm-mock-server/src/server.ts

There is no out-of-the-box mock for subscriptions in the Apollo packages, so these were implemented using the WebSockets and an in-memory PubSub, as described in the [Apollo Server docs](https://www.apollographql.com/docs/apollo-server/data/subscriptions).
Tested with several operations on the Inbox chats.

Add support for subscriptions to mock server

---

lib/providers/user_provider.dart
lib/widgets/molecules/recommended_mentors_scroll.dart

A couple changes which get the app into a more usable state when connected to the real backend.
1. ~~Hacky temp 'fix' on the provider avatar bug. The MMData backend doesn't provide URLs at this time for this field. As a more long term fix in the mmdata backend, we should provide a graphQL resolver for `avatarUrl` and rename the current field to `avatarPath` or something.~~ There is a [PR out](https://github.com/micromentor-team/mmdata/pull/286) in the backend which fixes this issue, not yet merged. This PR adds the fix for null avatar URLs used in `findAllUsers` to the `findMentorUsers` and `findMenteeUsers` queries.
2. Display only 10 Mentor users on the home page, rather than loading the entire users collection onto the app. The app is unusable when connected to the backend due to the …

Fix provider avatar, home page findAllUsers bugs

---

lib/__generated/schema/operations_channel.graphql.dart
lib/__generated/schema/operations_message.graphql.dart
lib/providers/channels_provider.dart
lib/providers/messages_provider.dart
lib/providers/models/chat_model.dart
lib/providers/models/inbox_chat_tile_model.dart
lib/schema/operations_channel.graphql
lib/schema/operations_message.graphql
lib/widgets/screens/channel_messages/channel_messages.dart
mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/queries.ts

Introduces channelChanged subscription event filtering so that models (a.k.a. ChangeNotifiers for UI components) only process events that are relevant to them. Since the type of event and channel/message id is now included in the subscription, event handling is now more specific and efficient:  we now refresh only the object that changed instead of refreshing all of the data for every event received.
Note that the frontend uses the models to implement optimistic updates, so that the UI is updated without querying the backend. An eventual 'refresh' with the backend data ensures that both backend and frontend are synced.
Includes several other fixes and improvements, but as indicated in the TODOs, there is still more work to do in regards to optimization.

Improved event handling for channel messages

---

mm-mock-server/src/mocks/util/generators.ts
mm-mock-server/src/mocks/util/state.ts
mm-mock-server/src/server.ts

The findUsers query with GroupMemberships was not working with the mock server. Some variables were misnamed and we also needed a resolver for the IGroupMembership type.

Fix GroupMemberships on mock server

---

lib/l10n/app_en.arb
lib/widgets/screens/sign_up/mentor_or_entrepreneur.dart
lib/widgets/screens/sign_up/sign_up_bottom_buttons.dart
lib/widgets/screens/sign_up/sign_up_email.dart
lib/widgets/screens/sign_up/sign_up_icon_footer.dart
lib/widgets/screens/sign_up/sign_up_screen.dart
lib/widgets/screens/sign_up/sign_up_template.dart

1. Create a generic widget SignUpTemplate for sign up pages. 
2. Move bottom buttons widget to under sign up folder, and make it more customizable, as future pages would require changes in the onPressed functions and button texts.
3. Extracted footer to a standalone SignUpIconFooter widget for reuse.
4. Input validation for email page
(connected mentor page with sign up email page for testing purpose, I will update it in the future once we have more screens)

Refactored sign up related pages to use a generic widget SignUpTemplate

---

mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/queries.ts
mm-mock-server/src/mocks/util/generators.ts
mm-mock-server/src/mocks/util/state.ts

Makes the latest app version functional with the mock server. The following were added:
- Added query for myChannelInvitations
- Server state starts with both sent and received invitations
- Server stat starts with 2 ongoing conversations, one with unseen messages, the other without
- Withdraw sent invitations

Update mock server resolvers and state to handle new inbox features

---

android/app/src/debug/AndroidManifest.xml

This completes the changes originally made in https://github.com/micromentor-team/mm-flutter-app/pull/108. Without it it's impossible to run `flutter run` for me.

Make it possible again to run debug version of the app

---

lib/__generated/schema/operations_user.graphql.dart
lib/__generated/schema/schema.graphql.dart
lib/providers/user_provider.dart
lib/schema/operations_user.graphql
lib/schema/schema.graphql
mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/util/generators.ts
mm-mock-server/src/mocks/util/state.ts

Started these changes a couple of weeks ago while working on the backend's matching engine.
Goal:
- schema updates to match latest backend (done)
- updates to mock server for UserSearch api calls (partly done)
- updates to providers to allow for searches with filters (done)
TODO:
~~- add additional fields to the User provider (e.g. pronouns, cityOfOrigin, etc) that will be used on the detailed profile page~~
~~- remove changes to explore.dart screen, the scope of this PR is already too big~~

Matching, profile updates to match backend progress

---

lib/l10n/app_en.arb
lib/widgets/molecules/upload_photo_button.dart
lib/widgets/screens/sign_up/mentor_or_entrepreneur.dart

This PR implements the photo upload widget:
1. Big button that triggers a popup with two options.
2. The popup appears on top of a scrim that blocks user interaction with the components underneath it.

Photo upload widget 

---

lib/__generated/schema/operations_content.graphql.dart
lib/main.dart
lib/providers/content_provider.dart
lib/schema/operations_content.graphql
lib/widgets/molecules/checkbox_list_and_form.dart
lib/widgets/molecules/multi_select_chips.dart
lib/widgets/screens/sign_up/sign_up_business_add_pronouns.dart
lib/widgets/screens/sign_up/sign_up_business_help_selection.dart
lib/widgets/screens/sign_up/sign_up_business_industry.dart
lib/widgets/screens/sign_up/sign_up_mentor_pronouns.dart
lib/widgets/screens/sign_up/sign_up_template.dart

Fetches options from the backend using the content provider. This PR integrates the expertise picker, the pronoun picker, and the industry picker. This should cover the entire entrepreneur flow.
Note that some functions with hardcoded data were left in some classes because these are being used in the pages that Rupal is working on, so I chose not to delete them to avoid conflicts. These should be cleaned up as soon as we integrate the mentor's flow with the content provider.

Entrepreneur signup flow with content provider

---

lib/__generated/schema/operations_content.graphql.dart
lib/__generated/schema/operations_user.graphql.dart
lib/__generated/schema/schema.graphql.dart
lib/providers/user_provider.dart
lib/schema/operations_user.graphql
lib/schema/schema.graphql

Fixes an issue which may be blocking #139, the lack of paginated user search results.
`topUserIds` from the searches only included the top 10 users from a search. The search results exposed here will allow us to get more results. Right now, it allows us to fetch the entire list, so I recommend using some variables like this to limit the response to a reasonable number at first:
```json
{
"userSearchId":"6514ab0174d1baabebddca7c",
"options": {
"limit": 10,
"skip": 0
}
}
```

Add paginated user search results to user provider

---

lib/main.dart
lib/providers/models/chat_model.dart
lib/providers/models/inbox_model.dart
lib/providers/models/scaffold_model.dart
lib/widgets/molecules/invitation_section.dart
lib/widgets/screens/inbox/inbox_chat_list.dart
lib/widgets/screens/inbox/inbox_invites_received.dart
lib/widgets/screens/inbox/inbox_invites_sent.dart
lib/widgets/screens/inbox/invitation_detail.dart
lib/widgets/screens/profile/profile.dart
lib/widgets/screens/profile/profile_page_header.dart
pubspec.lock
pubspec.yaml

This introduces additional improvements to the InboxModel:
- The redundant queries were consolidated to reduce data utilization.
- Polls the backend at regular intervals to retrieve new invitations received, new channels created, or determine if a sent invitation has been accepted or declined. This is necessary because subscriptions require an existing channel, and the events mentioned lack a channel to subscribe to. The scope of the poll will eventually be reduced to only include the most recent data to avoid wasteful data utilization.
- InboxModel Selectors were overriden to only rebuild widgets when certain model fields change, AND the model is not in a loading state. This is extremely important when polling because we do not want the screen to be rebuilding every time a poll occurs, …

Inbox polling & improved Selectors

---

lib/__generated/schema/operations_user.graphql.dart
lib/main.dart
lib/providers/content_provider.dart
lib/providers/models/explore_card_filters_model.dart
lib/providers/user_provider.dart
lib/schema/operations_user.graphql
lib/widgets/atoms/autocomplete_widget.dart
lib/widgets/atoms/explore_filter.dart
lib/widgets/atoms/skill_chip.dart
lib/widgets/molecules/autocomplete_picker.dart
lib/widgets/molecules/profile_quick_view_card.dart
lib/widgets/screens/explore/explore.dart
lib/widgets/screens/explore/recommended_mentors_filters.dart
lib/widgets/screens/explore/recommended_mentors_filters_advanced.dart
lib/widgets/screens/inbox/invitation_detail.dart
lib/widgets/screens/profile/invite_to_connect.dart
mm-mock-server/src/mocks/mutations.ts

This PR tries to make "Explore" screen show data retrieved from a backend instead of using hardcoded values. This is done by calling `FindRecommendedUsers` query (similar to `FindMentorUsers` and `FindMenteeUsers`) using `matchInput` generated from `ExploreCardFiltersModel`.
There are a few quirks about this PR that make it more of a "draft" right now:
1.  Since pagination is not implemented by any backend, support for this feature is skipped for now. Instead, each time a user hits the "See More" button, a new full list is retrieved with five more entries than before, replacing the previous list.
Unfortunately, as I've tried to use `Future<OperationResult<T>>` pattern that I've observed in other widgets, it fails to work when its value is replaced. I don't know exactly why is that and …

Connect Explore screen to a backend

---

lib/widgets/screens/sign_up/sign_up_entrepreneur_website.dart

This PR contains 2 changes:
1. Allow entrepreneur/mentee users to continue through signup without entering a website
2. Show "dual-role" users (who are both mentors and mentees) in search results
For the optional input, I wasn't sure if we have a specific way to implement this.
2 isn't scoped for this app but it is a use case the MicroMentor will need to support, feel free to reject if it seems like it's outside the scope for the open source app. In that case I can revert that commit and merge this without that change.

Website signup -> optional, support "dual-role" users

---

lib/utilities/scaffold_utils/user_popup_menu_button.dart

Channels were not being updated locally after archiving/unarchiving from the overflow menu. Users only saw the update after polling occurs. This PR makes it so that local changes are applied immediately.

Update inboxModel when archiving/unarchiving chats from overflow menu

---

lib/constants/numerical.dart
lib/providers/messages_provider.dart
lib/providers/models/chat_model.dart
lib/widgets/screens/inbox/channel_messages/channel_messages_screen.dart

Fetches the most recent messages of a chat whenever it is opened, and only fetch older messages as the user scrolls up. This allows opening the chat very quickly and reduce data utilization since it is not expected users need the entire history of chat messages every time they open a conversation.
This video demonstrates the feature with a conversation that has a very large number of messages:
[lazy_loading.webm](https://github.com/micromentor-team/mm-flutter-app/assets/25093428/6d30d4bc-1241-4379-b8b7-ffa56477f5a4)

Channel messages infinite scrolling with lazy loading

---

lib/__generated/schema/operations_invitation.graphql.dart
lib/__generated/schema/schema.graphql.dart
lib/providers/invitations_provider.dart
lib/providers/models/inbox_model.dart
lib/schema/operations_invitation.graphql
lib/schema/schema.graphql
lib/widgets/features/home/components/invitation_section.dart
lib/widgets/features/home/components/profile_header.dart
lib/widgets/features/inbox/components/inbox_list_tile.dart
lib/widgets/features/inbox/inbox_invitation_detail.dart
lib/widgets/features/inbox/inbox_invites_received.dart
lib/widgets/features/inbox/inbox_invites_sent.dart
mm-mock-server/src/mocks/mutations.ts
mm-mock-server/src/mocks/util/generators.ts

Received invitations are marked as read whenever the user opens the invitation detail page. At this point the inbox invite notification for this specific invitation is removed, regardless if the invite was not accepted or declined. I also added a plain notification bubble in the inbox received invitations list tiles whenever the invitation hasn't been opened.
Modified the mock server to support new field readByRecipientAt.
The following video shows the feature in action:
[received-invites-read-receipt.webm](https://github.com/micromentor-team/mm-flutter-app/assets/25093428/a6daa63e-3533-4d18-b2e7-42928442a5b7)

Enable marking received invitations as read

---

lib/main.dart
lib/services/firebase/firebase_service.dart

Minor changes - in the debugger there was an exception when `_tokenSubscriptionStream.cancel();` was called, which this fixes. Not sure if that has any effect on the app.
In my local, I am unable to view the app's onboarding flow after pressing "Get Started", which is what this PR was attempting to fix.

Fix late variable error, relative import

---

lib/widgets/features/sign_up/components/sign_up_template.dart

For some reason this widget makes it impossible to see the SignUp flow in the web version. Figured it was easier to remove it, since all it does is add a subtle fade effect at the top of the screen when scrolling vertically. No one will miss having this.

Remove ShaderMask from signup flow to fix Web issues

---

mm-mock-server/src/mocks/util/generators.ts
mm-mock-server/src/mocks/util/state.ts

- Adds 'filter' to UserSearchInput in mock server, which was added to backend in https://github.com/micromentor-team/mm-flutter-app/pull/183. Without this the recommended section (Home) and the Explore page don't show any results.
- Remove reply comments from mock conversations, since replies are no longer supported by the UI (even though the code is still there for whenever this gets added again)

Minor mock server fixes: UserSearchInput & chat replies

---

lib/utilities/router.dart
lib/widgets/features/sign_up/screens/sign_up_birth_year.dart
lib/widgets/features/sign_up/screens/sign_up_credentials.dart
lib/widgets/features/sign_up/screens/sign_up_entrepreneur_company_name.dart
lib/widgets/features/sign_up/screens/sign_up_entrepreneur_company_stage.dart
lib/widgets/features/sign_up/screens/sign_up_expertises.dart
lib/widgets/features/sign_up/screens/sign_up_gender.dart
lib/widgets/features/sign_up/screens/sign_up_group_membership.dart
lib/widgets/features/sign_up/screens/sign_up_language.dart
lib/widgets/features/sign_up/screens/sign_up_location.dart
lib/widgets/features/sign_up/screens/sign_up_mentor_role.dart
lib/widgets/features/sign_up/screens/sign_up_method.dart
lib/widgets/features/sign_up/screens/sign_up_phone.dart
lib/widgets/features/sign_up/screens/sign_up_reason.dart

This PR makes it so that users can navigate back and forward in the signup flow pages without losing the values that were previously entered.
This is done primarily in two ways:
1. PageRoutes in the router are set to maintain state, which means that once created the screens will remain active and maintain the state of their variables even if there is another page in the top of the navigation stack. This helps when navigating to previous pages. * Note that performance is not a concern here because there can only be one copy of each signup screen in the navigation stack, and the stack is cleared once signup completes.
2. The Stateful Widget screens are initialized using values from the UserRegistrationModel, if any. This helps when navigating forward to a page you had filled out already, …

Initialize and maintain state during signup flow

---

README.md
android/app/src/main/AndroidManifest.xml
lib/widgets/shared/radio_button_cards.dart

- Per UX request, make entire radio button card (used during signup flow user type and business stage selection) clickable. Adjust paddings.
- Fixes issues with handling the Android device's back button on API 34+, which would always cause the app to be closed instead of navigating to the previous page. The fix involves removing an entry from the Android manifest, which is suggested in [this issue](https://github.com/flutter/flutter/issues/117061).
- Remove sections on Widgetbook and testing from the README, since the app currently doesn't support these. This was done to avoid confusing new engineers and partners reading the document.

Misc fixes: Android back navigation, README update, UI tweaks
