micromentor-team/mentoring-flutter-app

- .git-hooks/pre-commit
- .github/workflows/documentation.yaml
- README.md
- devenv.nix
This PR formats `README.md` and ensures any future commits will compy with [GitHub Flavored Markdown spec](https://github.github.com/gfm/). It does that by "converting" from markdown to markdown using [pandoc](https://pandoc.org/) and checking if there is any difference.
My experience is that if many people touch the same markdown document using different styling it quickly becomes a mess that discourages future contributions.
> Ensure README is properly formatted

- lib/constants/styles.dart
- lib/constants/themes.dart
- lib/widgets/atoms/rectangle_button.dart
TextButton is used in different screens with different design expectations, therefore it cannot be styled in the app Theme
> Extract TextButtonStyle from theme

- mm-mock-server/src/mocks/mutations.ts
- mm-mock-server/src/mocks/util/generators.ts
- mm-mock-server/src/mocks/util/state.ts
Work in progress. Will add any generators or states needed for the mock server updates in the mentor request iteration.
Not sure if any additional changes are needed, will check with @shadowbrush on this in a bit.
> Mock server updates for mentor request iteration

- lib/data/models/user/user_api.dart
- lib/data/models/user/user_provider.dart
- lib/utilities/errors/crash_handler.dart
- lib/widgets/atoms/reminder_banner.dart
- lib/widgets/screens/dashboard/dashboard.dart
- mm-mock-server/schema.graphql
- mm-mock-server/src/mocks/queries.ts
- mm-mock-server/src/mocks/util/generators.ts
1. Add profile completion percentage and last update in mock server user schema, add an api getUserProfileInfo  for getting these two fields
2. The app queries mock backend for user info and renders the banner accordingly
3. (small fix) FirebaseCrashlytics doesn't support web app, so I added an extra condition 
next step would be to update onError to use crashHandler.
> Backend for reminder banner

- .envrc
- devenv.nix
This PR updates devenv config after changes made at https://github.com/micromentor-team/mm-flutter-app/pull/30.
> Devenv update

- lib/constants/dimensions.dart
- lib/constants/routes.dart
- lib/l10n/app_en.arb
- lib/main.dart
- lib/utilities/router.dart
- lib/widgets/molecules/closable_tile.dart
- lib/widgets/molecules/explore_bottom_buttons.dart
- lib/widgets/molecules/image_tile.dart
- lib/widgets/molecules/profile_quick_view_card.dart
- lib/widgets/screens/explore/explore.dart
- lib/widgets/screens/explore/invite_to_connect.dart
- lib/widgets/screens/inbox/invite_to_connect.dart
https://github.com/micromentor-team/mm-flutter-app/assets/100324646/bd1553a7-d314-4c05-bab4-f140e76f5b63
---
1. Invite to connect page: sends connect invites to one to multiple users. When multiple users are selected, show a scroll of user names and profile image. When only one user is selected, show a quick view card.
2. Refactor: move ProfileQuickViewInfo and helper functions to profile_quick_view_card.dart to make it reusable across files
> Invite-to-connect page

- lib/constants/routes.dart
- lib/l10n/app_en.arb
- lib/providers/models/scaffold_model.dart
- lib/utilities/router.dart
- lib/utilities/scaffold_utils/appbar_factory.dart
- lib/widgets/screens/inbox/inbox_invites_received.dart
- lib/widgets/screens/inbox/inbox_invites_sent.dart
- lib/widgets/screens/inbox/new_invite_detailed_profile.dart
- lib/widgets/screens/new_invite_detailed_profile.dart
In the spirit of having smaller PRs and getting help quickly, I have created this PR.
This PR does the following:
- It shows "New Invites" that come for the user.
- Currently, the profile cards, date, time, and the new invite message is hardcoded. 
I need help with:
- Figuring out a way to remove "Invites + Recieved + Sent" appBar from the top of the page. I have played around with the code, but it isn't clear to me yet how I can remove this appBar.
Next steps for this item would be to:
- Use non-hardcoded profile cards, date, time, and the new invite message
> New invite request - UI Iteration 1

- lib/constants/routes.dart
- lib/l10n/app_en.arb
- lib/providers/explore_card_filters_provider.dart
- lib/utilities/router.dart
- lib/widgets/atoms/clear_apply_buttons.dart
- lib/widgets/molecules/autocomplete_picker.dart
- lib/widgets/molecules/recommended_mentors_filters.dart
- lib/widgets/molecules/recommended_mentors_filters_advanced.dart
This PR adds a view for advanced filters, similarly to https://github.com/micromentor-team/mm-flutter-app/pull/66. I've also performed a minor cleanup.
> Advanced filters

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- lib/l10n/app_en.arb
- lib/widgets/molecules/profile_experience_and_education.dart
- lib/widgets/screens/profile/profile.dart
- pubspec.lock
- pubspec.yaml
The underlying data is hardcoded because the `User` model:
1) Doesn't have education data
2) Contains a `Company` structure but it seems to be related only to founded busiesses
> Add experience and education info to profile overview

- lib/l10n/app_en.arb
- lib/widgets/atoms/profile_chip.dart
- lib/widgets/screens/profile/how_can_i_help_section.dart
- lib/widgets/screens/profile/profile.dart
- lib/widgets/screens/profile/profile_basic_info.dart
Created "how can i help" section, including expertises/industries/availability/expectations subsections.
Using hardcoded chips, icon and text because we plan to retrieve these data from the backend in the future.
> Add section "how can i help" for mentors

- android/app/build.gradle
Made some changes to the gradle config file to allow the app to be built for release to the Play store.
> Gradle updates to release app

- lib/l10n/app_en.arb
- lib/widgets/screens/profile/profile.dart
- lib/widgets/screens/profile/profile_about_me.dart
> About me section of the profile page

- lib/__generated/schema/operations_channel.graphql.dart
- lib/__generated/schema/operations_message.graphql.dart
- lib/__generated/schema/schema.graphql.dart
- lib/providers/messages_provider.dart
- lib/schema/operations_channel.graphql
- lib/schema/operations_message.graphql
- lib/schema/schema.graphql
Allows us to know which message, channel, or invitation was updated. It also includes the participant ID.
Matching changes from this PR: https://github.com/baragaun/channels-service/pull/15/files#diff-a516eb7d3ce3fe6d07d2ffca3665eff92d31c0674795b7256a7b71323687eef5
> Add channels subscription to graphql schema

- lib/main.dart
- lib/providers/base/base_provider.dart
- lib/providers/channels_provider.dart
- lib/providers/messages_provider.dart
- lib/providers/user_provider.dart
- lib/utilities/utility.dart
- lib/widgets/atoms/reminder_banner.dart
- lib/widgets/molecules/invitation_section.dart
- lib/widgets/molecules/recommended_mentors_scroll.dart
- lib/widgets/screens/dashboard/dashboard.dart
- lib/widgets/screens/sign_up/sign_up_screen.dart
This completes the migration to using asynchronous queries instead of Widget inside our 'Provider' classes.
Did some cleanup and small optimizations where appropriate.
> Refactor UserProvider to use Future instead of Widgets

- lib/__generated/schema/operations_content.graphql.dart
- lib/__generated/schema/schema.graphql.dart
- lib/schema/operations_content.graphql
- lib/schema/schema.graphql
- Added `includeArchived` boolean attribute on `FindObjectsOptions` (for graphql queries)
- Changed names of language fields for clarity as to their function
See this doc for an explanation on the language fields:  https://github.com/baragaun/secureid-service/blob/82473136d97ddcac2048c5610ff3f55d6e8a1ff1/src/services/secureId/docs/handling-user-languages.md
Probably not too relevant at this moment to the wider team, since the Flutter app doesn't yet rely on these fields for any logic.
> Changes to backend schema (languages, archiving)

- lib/widgets/screens/inbox/inbox_chat_list.dart
This addresses the race condition created when archiving/unarchiving a channel via the dismissable tiles. The UI needs to be refreshed immediately after dismissing, but not before the update is completed in the backend. This solution uses retry queries with exponential backoff to ensure the update is completed before proceeding with the refresh.
A similar approach could be used for other race conditions, given that the majority of mutations execute asynchronously.
> Use polling to refresh UI only after isArchived update is live

- lib/__generated/schema/operations_user.graphql.dart
- lib/__generated/schema/schema.graphql.dart
- lib/schema/schema.graphql
- lib/widgets/atoms/reminder_banner.dart
- lib/widgets/screens/inbox/new_invite_detailed_profile.dart
Removes the `UserExt` class from the graphql schema and reverts some changes to the `User` resolver
> Revert some updates to graphql schema

- lib/widgets/atoms/reminder_banner.dart
- lib/widgets/molecules/inbox_chat_list_tile.dart
- lib/widgets/screens/channel_messages/channel_messages.dart
- lib/widgets/screens/channel_messages/message_bubble/message_bubble.dart
- lib/widgets/screens/channel_messages/message_details.dart
- lib/widgets/screens/inbox/inbox_chat_list.dart
- lib/widgets/screens/inbox/inbox_invites_received.dart
- lib/widgets/screens/inbox/new_invite_detailed_profile.dart
All dates and times were being displayed in UTC. This commit ensures that displayed times are in the user's timezone.
Please merge after approving.
> Apply local timezone to all DateTime displayed in the UI

- lib/main.dart
Reverts micromentor-team/mm-flutter-app#111
Adds the Welcome screen back now that the testing session is over and we will start working on the sign up flow.
> Revert "Temporarily remove Welcome screen from sign-in flow for testing session"

- lib/__generated/schema/operations_channel.graphql.dart
- lib/__generated/schema/schema.graphql.dart
- lib/providers/channels_provider.dart
- lib/providers/messages_provider.dart
- lib/schema/operations_channel.graphql
- lib/schema/schema.graphql
Update to the latest schema. The following breaking changes were resolved:
- FindObjectOptions.IncludeDeleted now takes an IncludeFilterOption instead of a boolean
- It is now necessary to add FindObjectOptions.IncludeArchived to findChannelsForUser, otherwise only unarchived channels are included in the query
> Update schema and reconcile breaking changes

- lib/constants/routes.dart
- lib/l10n/app_en.arb
- lib/utilities/router.dart
- lib/widgets/atoms/text_form_field_widget.dart
- lib/widgets/screens/sign_up/sign_up_email.dart
- lib/widgets/screens/sign_up/sign_up_password.dart
Make text form field widget work for passwords - adding icon to show/hide input
https://github.com/micromentor-team/mm-flutter-app/assets/100324646/fee4aa0b-aec6-47b5-ade2-12eec5138d9e
Future TODOs: add more checks on password, including strength, length, etc. and show the info on password screen.
> Sign up password page part 1

- lib/l10n/app_en.arb
- lib/widgets/molecules/multi_select_chips.dart
This widget allows the user to select a given number of options by tapping on the chips.
**Part 1 of the widget implements the following functionality**
- The two main parts of this widget are: text at the top of the list, and the list itself.
- The generic widget currently allows passing parameters for the title, and the list of chips (each chip has an optional icon and a required text).
**Part 2 of this widget would iterate on this chip to do the following:**
- the generic widget would allow passing the parameter for the maximum number of selections
- If the maximum number of chips is selected, tapping on additional chips has no effect. The user can always deselect a previous selection and then select a new one.
> Part 1 of the multi-select chip

- lib/constants/routes.dart
- lib/l10n/app_en.arb
- lib/utilities/router.dart
- lib/widgets/screens/sign_up/sign_up_community_guidelines.dart
- lib/widgets/screens/sign_up/sign_up_permissions.dart
- lib/widgets/screens/sign_up/sign_up_welcome.dart
https://github.com/micromentor-team/mm-flutter-app/assets/100324646/792df7c8-5622-4c44-8730-544e54825672
> Sign up permissions and community guidelines page

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner/Info.plist
- ios/Runner/Runner.entitlements
Added some changes made here while following some guides to set up an iOS deployment manually, which I see as a precursor to getting the CI/CD set up for iOS. (guides: https://docs.flutter.dev/deployment/ios, https://firebase.flutter.dev/docs/messaging/apple-integration#next-steps, https://firebase.google.com/docs/cloud-messaging/ios/client)
> Add capabilities and other minor ios config changes

- lib/__generated/schema/operations_content.graphql.dart
- lib/__generated/schema/schema.graphql.dart
- lib/main.dart
- lib/providers/content_provider.dart
- lib/schema/operations_content.graphql
- lib/schema/schema.graphql
Fixes an issue which was present in #158 in the signup flow, where the pronoun options weren't loaded from the backend.
> Provide pronouns along with other options

- lib/l10n/app_en.arb
- lib/widgets/features/profile/components/big_profile_chip.dart
- lib/widgets/features/profile/components/edit_experience_and_education.dart
- lib/widgets/features/profile/components/edit_how_can_i_help.dart
- lib/widgets/features/profile/edit_profile.dart
Added how can I help, my education and my experience section in edit profile screen. 
The last piece will be about my business for entrepreneur users.
https://github.com/micromentor-team/mm-flutter-app/assets/100324646/f2fbb72b-a691-428f-837f-ece97c0f2ff4
> Edit profile screen part 2
